# Generated by Django 6.1.1 on 2026-09-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text="Describe the lesson's setting or context.")),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(help_text='Traditional Chinese form; used as the primary display form.', max_length=100)),
                ('simplified', models.CharField(blank=True, max_length=100)),
                ('pinyin', models.CharField(help_text='Use tone marks (for example, nǐ hǎo) and separate syllables with spaces.', max_length=200)),
                ('english', models.CharField(max_length=255, verbose_name='English translation')),
            ],
            options={
                'ordering': ('traditional', 'pinyin'),
                'constraints': [models.UniqueConstraint(fields=('traditional', 'pinyin'), name='unique_word_traditional_pinyin')],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='lessons.lesson')),
                ('words', models.ManyToManyField(blank=True, related_name='sentences', to='lessons.word')),
            ],
            options={
                'ordering': ('lesson', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='vocabulary',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lessons.word'),
        ),
    ]
