# Generated by Django 6.1.1 on 2026-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='simplified',
            field=models.CharField(max_length=100),
        ),
    ]
