# Generated by Django 6.1.1 on 2026-09-27 04:50

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_vocabulary_links(apps, schema_editor):
    """Carry links from Django's original implicit M2M table into LessonWord."""
    connection = schema_editor.connection
    tables = set(connection.introspection.table_names())
    old_table = "lessons_lesson_vocabulary"
    if old_table not in tables:
        return

    with connection.cursor() as cursor:
        cursor.execute(
            f'SELECT lesson_id, word_id FROM "{old_table}" ORDER BY lesson_id, id'
        )
        links = cursor.fetchall()

    LessonWord = apps.get_model("lessons", "LessonWord")
    positions = {}
    for lesson_id, word_id in links:
        positions[lesson_id] = positions.get(lesson_id, 0) + 1
        LessonWord.objects.using(connection.alias).create(
            lesson_id=lesson_id,
            word_id=word_id,
            section="vocabulary",
            position=positions[lesson_id],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_word_simplified'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name='LessonWord',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('section', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('phrases', 'Phrases'), ('proper_nouns', 'Proper Nouns'), ('supplementary', 'Supplementary Vocabulary')], default='vocabulary', max_length=20)),
                        ('position', models.PositiveIntegerField(help_text='Order within this section, starting at 1.')),
                        ('part_of_speech', models.CharField(blank=True, max_length=80)),
                        ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to='lessons.lesson')),
                        ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_entries', to='lessons.word')),
                    ],
                    options={
                        'ordering': ('section', 'position', 'id'),
                        'constraints': [
                            models.UniqueConstraint(fields=('lesson', 'word'), name='unique_word_per_lesson'),
                            models.UniqueConstraint(fields=('lesson', 'section', 'position'), name='unique_lesson_section_position'),
                        ],
                    },
                ),
                migrations.RunPython(copy_existing_vocabulary_links, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
            name='LessonWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('phrases', 'Phrases'), ('proper_nouns', 'Proper Nouns'), ('supplementary', 'Supplementary Vocabulary')], default='vocabulary', max_length=20)),
                ('position', models.PositiveIntegerField(help_text='Order within this section, starting at 1.')),
                ('part_of_speech', models.CharField(blank=True, max_length=80)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_entries', to='lessons.lesson')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_entries', to='lessons.word')),
            ],
                    options={
                        'ordering': ('section', 'position', 'id'),
                        'constraints': [
                            models.UniqueConstraint(fields=('lesson', 'word'), name='unique_word_per_lesson'),
                            models.UniqueConstraint(fields=('lesson', 'section', 'position'), name='unique_lesson_section_position'),
                        ],
                    },
                ),
                migrations.AlterField(
                    model_name='lesson',
                    name='vocabulary',
                    field=models.ManyToManyField(blank=True, related_name='lessons', through='lessons.LessonWord', to='lessons.word'),
                ),
            ],
        ),
    ]
