# Generated by Django 6.1.1 on 2026-09-27

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_lessons_to_textbook(apps, schema_editor):
    Source = apps.get_model("lessons", "Source")
    Lesson = apps.get_model("lessons", "Lesson")
    textbook, _ = Source.objects.using(schema_editor.connection.alias).get_or_create(
        name="Chinese textbook",
        defaults={"kind": "textbook"},
    )
    Lesson.objects.using(schema_editor.connection.alias).filter(source__isnull=True).update(source=textbook)


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_lessonword_alter_lesson_vocabulary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("kind", models.CharField(choices=[("textbook", "Textbook"), ("video", "Video"), ("other", "Other")], default="other", max_length=20)),
                ("url", models.URLField(blank=True, help_text="Optional link to the book, video, or other original material.")),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="lesson",
            name="source",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="lessons", to="lessons.source"),
        ),
        migrations.RunPython(assign_existing_lessons_to_textbook, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lesson",
            name="source",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lessons", to="lessons.source"),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(fields=("source", "title"), name="unique_lesson_title_per_source"),
        ),
    ]
