# Generated by Django 6.1.1 on 2026-09-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_source_lesson_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ("source__name", "title")},
        ),
    ]
