# Generated by Django 6.1.1 on 2026-09-27 05:12

from django.db import migrations, models


def copy_lesson_words(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    LessonWord = apps.get_model("lessons", "LessonWord")
    through = Lesson.vocabulary.through
    for row in LessonWord.objects.using(schema_editor.connection.alias).all().iterator():
        through.objects.using(schema_editor.connection.alias).get_or_create(
            lesson_id=row.lesson_id,
            word_id=row.word_id,
        )


def drop_legacy_automatic_table(apps, schema_editor):
    """Remove the unused implicit table left behind by migration 0003."""
    table_name = "lessons_lesson_vocabulary"
    if table_name in schema_editor.connection.introspection.table_names():
        quote = schema_editor.quote_name
        schema_editor.execute(f"DROP TABLE {quote(table_name)}")


def restore_lesson_words(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    LessonWord = apps.get_model("lessons", "LessonWord")
    through = Lesson.vocabulary.through
    positions = {}
    for row in through.objects.using(schema_editor.connection.alias).all().iterator():
        positions[row.lesson_id] = positions.get(row.lesson_id, 0) + 1
        LessonWord.objects.using(schema_editor.connection.alias).get_or_create(
            lesson_id=row.lesson_id,
            word_id=row.word_id,
            defaults={"section": "vocabulary", "position": positions[row.lesson_id]},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='vocabulary',
        ),
        migrations.RunPython(drop_legacy_automatic_table, migrations.RunPython.noop),
        migrations.AddField(
            model_name='lesson',
            name='vocabulary',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lessons.word'),
        ),
        migrations.RunPython(copy_lesson_words, restore_lesson_words),
        migrations.DeleteModel(
            name='LessonWord',
        ),
    ]
