# Generated by Django 6.1.1 on 2026-09-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_word_lesson_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnkiProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.BigIntegerField(unique=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('relearning', 'Relearning'), ('suspended', 'Suspended')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('again_count', models.PositiveIntegerField(default=0)),
                ('hard_count', models.PositiveIntegerField(default=0)),
                ('good_count', models.PositiveIntegerField(default=0)),
                ('easy_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField()),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anki_progress', to='lessons.word')),
            ],
        ),
    ]
